<a href="https://colab.research.google.com/github/ArturNakauchi/DataAnalysisPortfolio/blob/main/00_pytorchfundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00.PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

DBourke Github: https://github.com/mrdbourke/pytorch-deep-learning



##Importing and Checking Version

In [1]:
!nvidia-smi

Tue Apr 16 06:23:29 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


##Introduction to Tensors

torch.Tensor — PyTorch 2.2 documentation: https://pytorch.org/docs/stable/tensors.html#torch-tensor

In [6]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [12]:
# Get tensor back as Python int
scalar.item()

7

In [10]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [11]:
vector.shape

torch.Size([2])

In [13]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                         [3,6,9],
                         [2,4,5]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random Tensor

Why Random tensors?

Because neural networks start with Tensors with random numbrs and adjust these random numbers to represent the data.

`Start with random Numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch Random Tensors: https://pytorch.org/docs/stable/generated/torch.rand.html#torch-rand


In [25]:
# Random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2230, 0.5554, 0.1253, 0.2768],
        [0.3748, 0.5165, 0.1174, 0.4256],
        [0.2258, 0.7744, 0.6538, 0.2403]])

In [27]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

##Zeroes and Ones

In [29]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones.dtype

torch.float32

## Creating a Range of Tensors and Tensors-like

ARange documentation: https://pytorch.org/docs/stable/generated/torch.arange.html

In [41]:
#Use torch.arange()
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
#Creaing tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor Datatypes

**Notes** Tensor datatype is one of the 3 main issues with PyTorch and Deep Learning
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [47]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #what is the datatype(e.g. Float32, Float16)
                               device=None, #what device the tensor is on
                               requires_grad=False) #whether or not to track gradients with tensors operators
float_32_tensor

tensor([3., 6., 9.])

In [48]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [49]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [50]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

##Getting information from tensors (tensor attributes)

1. Tensor not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensor not right shape - to get shade from a tensor, use `tensor.shape`
3. Tensor not on right device - to get device drom a tensor, use `tensor.device`

In [52]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6590, 0.7679, 0.7657, 0.3092],
        [0.7052, 0.7324, 0.3733, 0.8439],
        [0.8657, 0.7832, 0.1805, 0.6779]])

In [56]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6590, 0.7679, 0.7657, 0.3092],
        [0.7052, 0.7324, 0.3733, 0.8439],
        [0.8657, 0.7832, 0.1805, 0.6779]])
Datatype of tensor: torch.float32
Shape of tensor: <built-in method size of Tensor object at 0x7c6cddd36570>
Device tensor is on: cpu


## Manipulating Tensors (Tensor Operations)

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix Multiplication

In [57]:
# Create a tensor and add 10

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [58]:
#Multiply by 10
tensor * 10

tensor([10, 20, 30])

In [59]:
#Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [60]:
#Try out Pytorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

## Matrix Multiplication

Two main ways to do it when talking about neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

Visuals: https://matrixmultiplication.xyz/


Two main rules to follow to perform matrix multiplication:
1. The **inner dimensions** must match:
- `(3,2) @ (3,2)` won't work
- `(3,2) @ (2,3)` will work
- `(2,3) @ (3,2)` will work

2. The resulting Matrix has the shape of the **outer dimensions**
- `(2,3) @ (3,2)` -> `(2,2)`
- `(3,2) @ (2,3)` -> `(3,3)`

In [62]:
#Element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [65]:
#Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [66]:
#Or
1*1 + 2*2 + 3*3

14

In [67]:
%%time
value = 0
for i in range(len(tensor)):
  value+= tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.83 ms, sys: 0 ns, total: 2.83 ms
Wall time: 4.2 ms


In [68]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 503 µs, sys: 0 ns, total: 503 µs
Wall time: 413 µs


tensor(14)

###Common error in matrix multiplications: shape errors

In [72]:
#Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
# torch.mm(tensor_A, tensor_B) #torch.mm is an alias for torch.matmult

In [73]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [74]:
#To fix this issue, transpose it

tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [78]:
print(f"Original shapes: tensor_A ={tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"Original shapes: tensor_A ={tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying {tensor_A.shape} @ {tensor_B.T.shape}")
print("Output: \n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape:{output.shape}")

Original shapes: tensor_A =torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
Original shapes: tensor_A =torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying torch.Size([3, 2]) @ torch.Size([2, 3])
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape:torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)


In [4]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [81]:
#Min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [82]:
#Max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [85]:
#Mean - Requires tensor of data type float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [86]:
#Sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [8]:
#Fiding the position of min and max. Returns the index
x.argmin()
x.argmax()

tensor(9)

##Reshaping, stacking, squeezing and unsqueezing tensors

- Reshaping - Reshapes an input to a defined shape
- View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
- Stacking - Combine multiple tensors on top of each other (vstack) or side by side(hstack)
- Squeeze - Removes all `1` dimensions from a tensor
- Unsqueeze - Adds a `1` dimention to a target tensor
- Permute - Return a view of the input with dimensions permuted(swapped) in a certain way


In [5]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [8]:
#Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [7]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [7]:
#Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [8]:
#Chaing z changes x (shares the same memory as the original input)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [11]:
#Stacking tensors
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [15]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
#Squeezing a tensor
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Squeezed tensor: {x_squeezed}")
print(f"Squeezed tensor shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New Squeezed tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Squeezed tensor shape: torch.Size([9])


In [18]:
#Unsqueeze a tensor
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew tensor shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

New tensor shape: torch.Size([1, 9])


In [21]:
#Permute a tensor - Rearranges the dimensions of a tensor in a specified order
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2, 0, 1) #shift the axis: 0->1, 1->2, 2->0
print(f"Previous shape {x_original}")
print(f"New shape {x_permuted}")

Previous shape tensor([[[0.9370, 0.1971, 0.4981],
         [0.5065, 0.2076, 0.5628],
         [0.0753, 0.6223, 0.3488],
         ...,
         [0.9062, 0.5046, 0.7857],
         [0.9976, 0.0739, 0.7104],
         [0.1590, 0.3249, 0.3736]],

        [[0.5083, 0.8140, 0.0324],
         [0.2471, 0.6891, 0.6527],
         [0.5630, 0.5622, 0.5899],
         ...,
         [0.6070, 0.6999, 0.0432],
         [0.3303, 0.4562, 0.2038],
         [0.8472, 0.0607, 0.2590]],

        [[0.3382, 0.4123, 0.2684],
         [0.8325, 0.7908, 0.9350],
         [0.7737, 0.4520, 0.8417],
         ...,
         [0.5133, 0.9048, 0.2089],
         [0.1694, 0.8748, 0.3766],
         [0.9669, 0.1147, 0.0591]],

        ...,

        [[0.9298, 0.3179, 0.7800],
         [0.0423, 0.5778, 0.6026],
         [0.8247, 0.4314, 0.4785],
         ...,
         [0.3951, 0.9283, 0.6208],
         [0.7775, 0.0249, 0.5198],
         [0.0201, 0.0122, 0.2588]],

        [[0.5978, 0.7962, 0.4661],
         [0.0340, 0.6493, 0.0945

##Indexing (Selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy


In [22]:
x = torch.arange(1, 10).reshape(1,3,3) #reshape is according to the size of the tensor's dimensions: 1 * 3 * 3 = 9
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [23]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
#index the middle bracket
x[0][0]

tensor([1, 2, 3])

In [25]:
#index the 1st element of the 1st dimention only
x[0][0][0]

tensor(1)

In [32]:
#index the second element of the second dimention
x[0][1][0]

tensor(4)

In [33]:
#use : to select all elements of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [34]:
#Get all values of the 0th and 1st dimention but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [35]:
#Get all values of the 0 dimension but only the 1 index of the 1st and 2nd dimension
x[:,1, 1]

tensor([5])

In [36]:
#get index 0 and 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [37]:
#index on x to return 9
x[0][2][2]

tensor(9)

In [43]:
#index to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch and NumPy

- Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
- PyTorch tensor ->NumPy -> `torch.Tensor.numpy()`

In [45]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #when converting from numpy to pytorch, pytorch will default to float64 unless specified
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [46]:
#Tensor to numpy changes dtype to float32
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducibility (Trying to take random out of random)

To ensure the neural network learns:

`starts with random numbers -> tensor operations -> update random numbers to try to make them better representations of data -> repeat`

To reduce the randomness in neural networks and PyTorch a **Random Seed**
A random seed reduces the "flavour" of randomness

Documentation: https://pytorch.org/docs/stable/notes/randomness.html

Wikipedia: https://en.wikipedia.org/wiki/Random_seed

In [49]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2049, 0.8623, 0.2665, 0.9067],
        [0.2873, 0.9967, 0.0723, 0.9718],
        [0.3701, 0.3176, 0.2391, 0.5580]])
tensor([[0.0568, 0.3550, 0.6201, 0.6730],
        [0.0776, 0.5590, 0.2305, 0.5595],
        [0.5878, 0.4624, 0.0167, 0.7832]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [53]:
#Set a random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##Running tensors and PyTorch objects on GPU

GPU = faster computation on numbers. NVidia Hardware + CUDA can increase the speed of computational power

Three Main Options:

1. Easiest - Google Colab
2. Use your own GPU
3. Use cloud computing like GCP, AWS, Azure

2 and 3 requires setup. Refer to PyTorch documentation.

In [6]:
#Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [8]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [9]:
#Count the number of devices
torch.cuda.device_count()

1

##Putting Tensors and models on the GPU

Putting things in the GPU means faster calculations



In [10]:
#Create a tensor
tensor = torch.tensor([1,2,3], device = "cpu")

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [11]:
#Move tensor to GPU if available

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Moving back to the CPU


In [14]:
# tensor_on_gpu.numpy()

In [13]:
#To fix the GPU tensor with NumPy issue, first set it to CPU
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3])