<a href="https://colab.research.google.com/github/ArturNakauchi/DataAnalysisPortfolio/blob/main/pytorch/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7,7)
random_tensor

tensor([[3.9338e-01, 1.8849e-02, 4.4398e-01, 7.9594e-01, 8.7736e-02, 5.0161e-01,
         6.6348e-01],
        [8.2287e-01, 5.1724e-01, 4.9618e-01, 6.5314e-01, 9.6159e-01, 5.8877e-04,
         8.8136e-01],
        [8.5753e-01, 2.5036e-01, 4.7542e-01, 3.8193e-01, 2.4619e-01, 7.9800e-01,
         3.5712e-01],
        [2.8642e-01, 6.7890e-01, 8.0681e-01, 2.3853e-01, 7.0629e-02, 3.6909e-01,
         6.0314e-01],
        [4.2294e-01, 1.9216e-01, 2.8316e-01, 1.2976e-02, 5.4689e-01, 9.8969e-01,
         5.2879e-01],
        [4.4955e-01, 3.9202e-01, 8.5831e-01, 2.4585e-01, 8.8605e-01, 4.9337e-01,
         6.2783e-03],
        [2.0638e-01, 3.7417e-01, 5.9743e-01, 3.8234e-01, 1.1977e-01, 4.6788e-01,
         1.7188e-01]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
random_tensor2 = torch.rand(1,7)
random_tensor2.shape
# Perform matrix multiplication
torch.matmul(random_tensor,random_tensor2.T)

tensor([[0.8155],
        [0.8802],
        [0.9850],
        [0.9800],
        [1.0728],
        [0.8524],
        [0.7443]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [10]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
random_tensor3 = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
random_tensor4 = torch.rand(1,7)

# Matrix multiply tensors
tensor_result = torch.matmul(random_tensor3,random_tensor4.T)
tensor_result, tensor_result.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [11]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [13]:
# Set random seed
torch.manual_seed(RANDOM_SEED)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
tensorA = torch.rand(2,3).to(device)
tensorB = torch.rand(2,3).to(device)
tensorA, tensorB

Device: cuda


(tensor([[0.4963, 0.7682, 0.0885],
         [0.1320, 0.3074, 0.6341]], device='cuda:0'),
 tensor([[0.4901, 0.8964, 0.4556],
         [0.6323, 0.3489, 0.4017]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
tensorC = torch.matmul(tensorA,tensorB.T)
tensorC, tensorC.shape

(tensor([[0.9722, 0.6174],
         [0.6292, 0.4455]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [16]:
# Find max
max = torch.max(tensorC)
# Find min
min = torch.min(tensorC)
max,min

(tensor(0.9722, device='cuda:0'), tensor(0.4455, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
arg_max = torch.argmax(tensorC)

# Find arg min
arg_min = torch.argmin(tensorC)
arg_max, arg_min

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_random = torch.rand(1,1,1,10)

# Remove single dimensions
squeezed_tensor = tensor_random.squeeze()

# Print out tensors and their shapes
tensor_random, squeezed_tensor

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))